// Code generated by "stringer -type ID -output ./token_string.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[J_NUMBER-0]
	_ = x[J_STRING-1]
	_ = x[J_BOOL-2]
	_ = x[J_NULL-3]
	_ = x[J_ARRAY-4]
	_ = x[J_OBJECT-5]
	_ = x[J_COMMENT-6]
	_ = x[J_OBJECT_KEY_VALUE_PAIR-7]
}

const _ID_name = "J_NUMBERJ_STRINGJ_BOOLJ_NULLJ_ARRAYJ_OBJECTJ_COMMENTJ_OBJECT_KEY_VALUE_PAIR"

var _ID_index = [...]uint8{0, 8, 16, 22, 28, 35, 43, 52, 75}

func (i ID) String() string {
	if i < 0 || i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
